// SPDX-License-Identifier: MIT

package certmanager

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime/schema"
)

// IssuerGVK 는 cert-manager Issuer CR (namespace-scope) 의 GroupVersionKind.
// AutoSelfSigned 패턴에서 operator 가 자동 생성하는 Issuer 의 apply 대상.
var IssuerGVK = schema.GroupVersionKind{
	Group:   certManagerGroup,
	Version: "v1",
	Kind:    "Issuer",
}

// BuildSelfSignedIssuer 는 self-signed Issuer (spec.selfSigned: {}) 의
// unstructured 표현을 반환한다. 사용자 IssuerRef 명시 없이 operator-issued
// root 로 TLS 를 활성하는 AutoSelfSigned 패턴 (외부 chart 의
// `tls.autoGenerated` 동등) 의 공통 골격.
//
// name 관례 ("<cluster>-selfsigned" 등) 와 label 셋 결정은 호출자 도메인
// 책임. labels 가 nil 또는 빈 map 이면 metadata.labels 미설정.
// CRD 미설치 cluster 에서는 apply 의 NoMatchError 를 호출자가 fail-soft 처리.
func BuildSelfSignedIssuer(name, namespace string, labels map[string]string) *unstructured.Unstructured {
	u := &unstructured.Unstructured{}
	u.SetGroupVersionKind(IssuerGVK)
	u.SetName(name)
	u.SetNamespace(namespace)
	if len(labels) > 0 {
		u.SetLabels(labels)
	}
	u.Object["spec"] = map[string]any{
		"selfSigned": map[string]any{},
	}
	return u
}
